; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "B16Raktár"
#define MyAppVersion "0.1.0.1"
#define MyAppPublisher "Blue16"
#define MyAppURL "http://www.blue16.hu:8082"
#define MyAppExeName "B16Raktar.exe"
#define MyProjectDir "e:\projects\b16depot\b16depot"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{306BFB4E-13D9-4248-B05E-F85D47269CC6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\B16Raktar
DefaultGroupName={#MyAppName}
OutputBaseFilename=B16Raktar_update
Compression=lzma
SolidCompression=yes
UsePreviousAppDir=yes
AllowNoIcons=yes
DisableDirPage=yes
UsePreviousTasks=yes
LanguageDetectionMethod=locale
CloseApplications=yes
CloseApplicationsFilter=B16Raktar

[InternetShortcut]
URL=http://www.blue16.hu:8082

[Types]



[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"

[LangOptions]



[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}" 
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"



[Files]
Source: "{#MyProjectDir}\target\B16Raktar.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyProjectDir}\target\spring-instrument-3.1.1.RELEASE.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyProjectDir}\setup\B16Raktar.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{group}\{#MyAppName}"; IconFilename: "{app}\B16Raktar.ico"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; IconFilename: "{app}\B16Raktar.ico"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{commonprograms}\My Program"; IconFilename: "{app}\B16Raktar.ico"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon
Name: "{commonstartup}\My Program"; IconFilename: "{app}\B16Raktar.ico"; Filename: "{app}\{#MyAppExeName}"
;Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon; WorkingDir: {app};
;Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon; WorkingDir: {app};

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


