#! /bin/sh
# preinst script for unibuild
#
# see: dh_installdeb(1)
set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
#
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)
        if id unibld >/dev/null 2>&1 ; then
                # We have a unibld user.
                if [ `id unibld -g -n` != "unibld" ] ; then
                        addgroup --system unibld || true
            #this can fail sometimes (i.e. with LDAP) so ignore it
                        usermod -g unibld unibld || true
                fi
        else
                adduser --system --group --quiet unibld
        fi


    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

